blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

login_check:
    path: /login_check

logout:
    path: /logout

api_login_check:
    path: /api/login_check
