<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getFormatted() {
        $query = $this->createQueryBuilder('c');
        $query->select('c.id', 'c.name')->indexBy('c', 'c.id');
        $result = $query->getQuery()->getResult();

        return $result;
    }
}
