<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getSubscribedUsers() {
        $query = $this
            ->createQueryBuilder('a')
            ->andWhere('a.subscribed = 1');

        return $query->getQuery()->getResult();
    }
}
