blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Article:index }

article_detail:
    path: /article/{id}
    defaults: { _controller: BlogBundle:Article:detail }
    requirements:
        id: \d+

category_list:
    path: /category/{id}
    defaults: { _controller: BlogBundle:Category:list }

article_create:
    path: /article/create
    defaults: { _controller: BlogBundle:Article:create, id: null }

article_delete:
    path: /article/{id}/delete
    defaults: { _controller: BlogBundle:Article:delete }
    methods: [POST]
    requirements:
        id: \d+

article_edit:
    path: /article/{id}/edit
    defaults: { _controller: BlogBundle:Article:create, id: null }

contact_create:
    path: /contact
    defaults: { _controller: BlogBundle:Contact:create}

login:
    path: /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: BlogBundle:Security:register }

rest_controller:
    type: rest
    resource: BlogBundle\Controller\RestController
    prefix: /api
