BlogBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: BlogBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            nullable: false
            unique: true
        email:
            type: string
            length: 255
            nullable: false
            unique: true
        password:
            type: string
            length: 255
            nullable: false
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        roles:
            type: array
        subscribed:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }

    oneToMany:
        comments:
            targetEntity: BlogBundle\Entity\Comment
            mappedBy: user
